__all__ = (
    "MAX_MESSAGE_LENGTH",
    "MAX_EMBED_TITLE_LENGTH",
    "MAX_EMBED_DESCRIPTION_LENGTH",
    "MAX_AUTOCOMPLETE_CHOICES",
)

MAX_MESSAGE_LENGTH: int = 2000

MAX_EMBED_TITLE_LENGTH: int = 256
MAX_EMBED_DESCRIPTION_LENGTH: int = 4096

MAX_AUTOCOMPLETE_CHOICES: int = 25
